name       : glibc
version    : 2.21
release    : 1
source     :
    - http://ftp.gnu.org/gnu/glibc/glibc-2.21.tar.xz : aeeb362437965a5d3f40b151094ca79def04a115bd363fdd4a9a0c69482923b8
license    : GPL-2.0
summary    : GNU C Library
emul32     : yes
clang      : no
autodep    : no
libsplit   : no
description: |
    GNU C Library
setup      : |
    export CFLAGS="-O3 -g -U_FORTIFY_SOURCE -fno-strict-aliasing \
                -fomit-frame-pointer -mno-tls-direct-seg-refs"
    if [ -e glibc-build ] ; then
        rm -fr glibc-build
    fi
    
    mkdir -v glibc-build && cd glibc-build
    
    
    if [ -n "$EMUL32BUILD" ]; then
        LEHOST="--host=i686-pc-linux-gnu"
        SLIBDIR="libc_cv_slibdir=/usr/lib32 --libdir=/usr/lib32"
    else
        export CC="gcc"
        SLIBDIR="libc_cv_slibdir=/usr/lib64 --libdir=/usr/lib64"
        LEHOST="--host=x86_64-evolveos-linux"
    fi
    
    ../configure \
       --with-tls \
       --with-__thread \
       --enable-bind-now \
       --enable-kernel=3.4.0 \
       --enable-stackguard-randomization \
       --without-cvs \
       --without-gd \
       --without-selinux \
       --disable-profile \
       --prefix=/usr \
       --mandir=/usr/share/man \
       --infodir=/usr/share/info \
       --libexecdir=/usr/lib/misc \
       --enable-obsolete-rpc \
       --bindir=/usr/bin \
       --sbindir=/usr/sbin \
       $CONFOPTS \
       $LEHOST \
       $SLIBDIR \
       --disable-static \
       --includedir=/usr/include \
       libc_cv_forced_unwind=yes \
       libc_cv_ctors_header=yes  \
       libc_cv_c_cleanup=yes  

build      : |
    cd glibc-build
    %make
install    : |
    cd glibc-build
    %make install install_root=%installroot%
