name       : mpfr
version    : 3.1.2
release    : 1
homepage   : http://www.mpfr.org
source     :
    - http://ftp.gnu.org/gnu/mpfr/mpfr-3.1.2.tar.xz : 399d0f47ef6608cc01d29ed1b99c7faff36d9994c45f36f41ba250147100453b
license    : GPL-2.0
summary    : The MPFR package contains functions for multiple precision math.
emul32     : yes
builddeps  :
    - gmp-devel
    - gmp-32bit
description: |
    The MPFR package contains functions for multiple precision math.
setup      : |
    %configure --disable-static --enable-thread-safe
build      : |
    %make
install    : |
    %make_install
    # We build 32-bit
    %make clean
