name       : gmp
version    : 6.0.0a
release    : 2
homepage   : http://gnu.org
source     :
    - http://ftp.gnu.org/gnu/gmp/gmp-6.0.0a.tar.xz : 9156d32edac6955bc53b0218f5f3763facb890b73a835d5e1b901dcf8eb8b764
license    : GPL-2.0
summary    : The GMP package contains math libraries. These have useful functions for arbitrary precision arithmetic
emul32     : yes
description: |
    The GMP package contains math libraries. These have useful functions for arbitrary precision arithmetic
setup      : |
    if [ -n "$EMUL32BUILD" ]; then
        export ABI=32
    fi
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    # We build 32-bit, distclean
    %make distclean
